# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNo', models.BigIntegerField(null=True, unique=True)),
                ('AccessToken', models.CharField(blank=True, max_length=300, null=True)),
                ('EmailId', models.EmailField(blank=True, max_length=254)),
                ('FirstName', models.CharField(blank=True, max_length=200)),
                ('LastName', models.CharField(blank=True, max_length=200)),
                ('password', models.CharField(blank=True, max_length=1000, null=True)),
                ('Address', models.CharField(blank=True, max_length=300, null=True)),
                ('logged_in', models.BooleanField(default=True)),
                ('Latitude', models.FloatField(blank=True, null=True)),
                ('Longitude', models.FloatField(blank=True, null=True)),
                ('AvgRating', models.FloatField(blank=True, default=3.0)),
                ('n', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
