# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserBase', '0011_auto_20170624_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='GcmId',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
