# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShopperPhoneNo', models.BigIntegerField(unique=True)),
                ('AadharImage', models.TextField(blank=True, null=True)),
                ('LicenseImage', models.TextField(blank=True, null=True)),
                ('VehicleRCImage', models.TextField(blank=True, null=True)),
                ('AadharURL', models.CharField(blank=True, max_length=500, null=True)),
                ('LicenseURL', models.CharField(blank=True, max_length=500, null=True)),
                ('VehicleRCURL', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shopper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('PhoneNo', models.BigIntegerField(unique=True)),
                ('password', models.CharField(blank=True, max_length=1000, null=True)),
                ('EmailId', models.EmailField(blank=True, max_length=254)),
                ('City', models.CharField(blank=True, default='Delhi', max_length=200, null=True)),
                ('DisplayPictureURL', models.CharField(blank=True, max_length=300, null=True)),
                ('AccessToken', models.CharField(blank=True, max_length=300, null=True)),
                ('IdNumber', models.CharField(blank=True, max_length=50)),
                ('IdType', models.CharField(blank=True, default='Aadhar Card', max_length=100)),
                ('Vehicle', models.CharField(blank=True, default='Car', max_length=50)),
                ('VehicleSpaceAvailable', models.IntegerField(blank=True, default=3, null=True)),
                ('AvailableDate', models.DateField(blank=True, max_length=20, null=True)),
                ('AvailableFrom', models.TimeField(blank=True, null=True)),
                ('AvailableTo', models.TimeField(blank=True, null=True)),
                ('IsOnline', models.BooleanField(default=False)),
                ('Latitude', models.FloatField(blank=True, null=True)),
                ('Longitude', models.FloatField(blank=True, null=True)),
                ('BankAccountNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('BankAccountType', models.CharField(blank=True, max_length=10, null=True)),
                ('BankName', models.CharField(blank=True, max_length=200, null=True)),
                ('BankBranch', models.CharField(blank=True, max_length=300, null=True)),
                ('BankBranchAddress', models.CharField(blank=True, max_length=300, null=True)),
                ('IFSCCode', models.CharField(blank=True, max_length=25, null=True)),
                ('AvgRating', models.FloatField(blank=True, default=3.0, null=True)),
                ('n', models.IntegerField(blank=True, default=0)),
                ('A', models.FloatField(blank=True, default=0)),
                ('B', models.FloatField(blank=True, default=0)),
                ('C', models.FloatField(blank=True, default=0)),
                ('D', models.FloatField(blank=True, default=0)),
                ('E', models.FloatField(blank=True, default=0)),
                ('Verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShopperImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShopperPhoneNo', models.BigIntegerField(unique=True)),
                ('DisplayPicture', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
