# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BatchBase', '0007_auto_20170719_0040'),
        ('Carts', '0010_remove_cartitem_proid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='BatchId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_items', to='BatchBase.Batch'),
        ),
    ]
