# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerPhoneNo', models.BigIntegerField(null=True)),
                ('PlacingTime', models.DateTimeField(auto_now_add=True)),
                ('Total', models.FloatField(blank=True, null=True)),
                ('DeliveryCharges', models.FloatField(blank=True, default=0.0, null=True)),
                ('Earnings', models.FloatField(blank=True, default=0.0, null=True)),
                ('DeliveryAddress', models.CharField(blank=True, max_length=300, null=True)),
                ('Latitude', models.FloatField(blank=True, null=True)),
                ('Longitude', models.FloatField(blank=True, null=True)),
                ('UserRating', models.FloatField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3.0)),
                ('ShopperRating', models.FloatField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3.0)),
                ('IsDelivered', models.BooleanField(default=False)),
                ('DeliveryDate', models.DateField(blank=True, max_length=20, null=True)),
                ('StartTime', models.TimeField(blank=True, null=True)),
                ('EndTime', models.TimeField(blank=True, null=True)),
                ('Notes', models.TextField(blank=True, null=True)),
                ('PriorityScore', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'ordering': ('DeliveryDate', 'StartTime'),
            },
        ),
    ]
