# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderBase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='DeliveryDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
