# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderBase', '0008_auto_20170706_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ShopperPhoneNo',
        ),
    ]
