# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderBase', '0009_remove_order_shopperphoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='DeliveryDate',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
    ]
