# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderBase', '0010_auto_20170713_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('DeliveryDate', 'StartTime')},
        ),
    ]
