# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OrderBase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.IntegerField(blank=True, null=True)),
                ('Quantity', models.FloatField(blank=True, default=1.0)),
                ('SubTotal', models.FloatField(blank=True, null=True)),
                ('Notes', models.TextField(blank=True, null=True)),
                ('OList', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='OrderBase.Order')),
            ],
        ),
    ]
