# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ShopperBase', '0001_initial'),
        ('OrderBase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Earnings', models.FloatField(blank=True, default=0.0)),
                ('PermanentShopper', models.BigIntegerField(blank=True, null=True)),
                ('PermanentAvailable', models.BooleanField(default=False)),
                ('TemporaryShopper', models.BigIntegerField(blank=True, null=True)),
                ('TemporaryAvailable', models.BooleanField(default=False)),
                ('IsDelivered', models.BooleanField(default=False)),
                ('OrderId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OrderBase.Order')),
                ('ShopperId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ShopperBase.Shopper')),
            ],
        ),
    ]
