# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShopperBase', '0009_auto_20170709_1823'),
        ('OrderBase', '0008_auto_20170706_2227'),
        ('BatchBase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Earning', models.FloatField(blank=True, default=0.0)),
                ('ShopperPhoneNo', models.BigIntegerField(blank=True, null=True)),
                ('OrderNo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OrderBase.Order')),
                ('ShopperId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ShopperBase.Shopper')),
            ],
        ),
        migrations.RemoveField(
            model_name='batches',
            name='ShopperId',
        ),
        migrations.DeleteModel(
            name='Batches',
        ),
    ]
