# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BatchBase', '0002_auto_20170711_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='Earning',
            new_name='Earnings',
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='ShopperPhoneNo',
            new_name='PermanentShopper',
        ),
        migrations.AddField(
            model_name='batch',
            name='IsDelivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batch',
            name='PermanentAvailable',
            field=models.BigIntegerField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='batch',
            name='TemporaryAvailable',
            field=models.BigIntegerField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='batch',
            name='TemporaryShopper',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
