# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-15 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'BatchBase', '0004_auto_20170715_1641'), (b'BatchBase', '0005_auto_20170715_1643')]

    dependencies = [
        ('BatchBase', '0003_auto_20170712_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='OrderNo',
            new_name='OrderId',
        ),
        migrations.AlterField(
            model_name='batch',
            name='PermanentAvailable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='batch',
            name='ShopperId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ShopperBase.Shopper'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='TemporaryAvailable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='batch',
            name='ShopperId',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ShopperBase.Shopper'),
        ),
    ]
