# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-14 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BatchBase', '0003_auto_20170712_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='OrderNo',
            new_name='OrderId',
        ),
        migrations.AlterField(
            model_name='batch',
            name='PermanentAvailable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='batch',
            name='TemporaryAvailable',
            field=models.BooleanField(default=False),
        ),
    ]
