# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-15 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShopperBase', '0010_auto_20170713_1733'),
        ('BatchBase', '0005_remove_batch_shopperid'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='ShopperId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ShopperBase.Shopper'),
        ),
    ]
