# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StoreId', models.IntegerField(blank=True, null=True, unique=True)),
                ('StoreLogoImage', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StoreName', models.CharField(blank=True, max_length=200, null=True)),
                ('StoreAddress', models.CharField(blank=True, max_length=300, null=True)),
                ('StoreLogo', models.CharField(blank=True, max_length=300, null=True)),
                ('Dealer_FirstName', models.CharField(blank=True, max_length=200, null=True)),
                ('Dealer_LastName', models.CharField(blank=True, max_length=200, null=True)),
                ('Dealer_ContactNo', models.BigIntegerField(blank=True, null=True)),
                ('Dealer_EmailId', models.EmailField(blank=True, max_length=254, null=True)),
                ('Dealer_password', models.CharField(blank=True, max_length=1000, null=True)),
                ('Dealer_Designation', models.CharField(blank=True, max_length=100, null=True)),
                ('Latitude', models.FloatField(blank=True, null=True)),
                ('Longitude', models.FloatField(blank=True, null=True)),
                ('CompanyLegalName', models.CharField(blank=True, max_length=300, null=True)),
                ('PANNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('BankAccountNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('BankAccountType', models.CharField(blank=True, max_length=10, null=True)),
                ('BankName', models.CharField(blank=True, max_length=200, null=True)),
                ('BankBranch', models.CharField(blank=True, max_length=300, null=True)),
                ('BankBranchAddress', models.CharField(blank=True, max_length=300, null=True)),
                ('IFSCCode', models.CharField(blank=True, max_length=25, null=True)),
                ('MondayOpeningTime', models.TimeField(blank=True, null=True)),
                ('TuesdayOpeningTime', models.TimeField(blank=True, null=True)),
                ('WednesdayOpeningTime', models.TimeField(blank=True, null=True)),
                ('ThursdayOpeningTime', models.TimeField(blank=True, null=True)),
                ('FridayOpeningTime', models.TimeField(blank=True, null=True)),
                ('SaturdayOpeningTime', models.TimeField(blank=True, null=True)),
                ('SundayOpeningTime', models.TimeField(blank=True, null=True)),
                ('MondayClosingTime', models.TimeField(blank=True, null=True)),
                ('TuesdayClosingTime', models.TimeField(blank=True, null=True)),
                ('WednesdayClosingTime', models.TimeField(blank=True, null=True)),
                ('ThursdayClosingTime', models.TimeField(blank=True, null=True)),
                ('FridayClosingTime', models.TimeField(blank=True, null=True)),
                ('SaturdayClosingTime', models.TimeField(blank=True, null=True)),
                ('SundayClosingTime', models.TimeField(blank=True, null=True)),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
    ]
