# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopperBase', '0009_auto_20170709_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopper',
            name='AvailableDate',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
    ]
