# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-15 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopperBase', '0010_auto_20170713_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopper',
            name='GcmId',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='shopper',
            name='City',
            field=models.CharField(blank=True, default='Delhi', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shopper',
            name='IdType',
            field=models.CharField(blank=True, default='Aadhar Card', max_length=100),
        ),
        migrations.AlterField(
            model_name='shopper',
            name='Vehicle',
            field=models.CharField(blank=True, default='Car', max_length=50),
        ),
    ]
