# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-14 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StoreBase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(blank=True, max_length=250)),
                ('Price', models.FloatField(blank=True, default=9.99)),
                ('StoreId', models.IntegerField(blank=True, null=True)),
                ('Category', models.CharField(blank=True, default='No Specific Category', max_length=200, null=True)),
                ('ProductImage', models.CharField(blank=True, max_length=400, null=True)),
                ('Features', models.TextField(blank=True, null=True)),
                ('ProductSize', models.IntegerField(blank=True, default=3, null=True)),
                ('Active', models.BooleanField(default=True)),
                ('RelatedStore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StoreBase.Store')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.IntegerField(blank=True, null=True, unique=True)),
                ('ProductString', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
