# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-15 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_auto_20170712_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.CharField(blank=True, default='No Specific Category', max_length=200, null=True),
        ),
    ]
